//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WpfApp1.ServiceReference1.CompositeType GetDataUsingDataContract(WpfApp1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WpfApp1.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistUser", ReplyAction="http://tempuri.org/IService1/isExistUserResponse")]
        bool isExistUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistUser", ReplyAction="http://tempuri.org/IService1/isExistUserResponse")]
        System.Threading.Tasks.Task<bool> isExistUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistUserAndPass", ReplyAction="http://tempuri.org/IService1/isExistUserAndPassResponse")]
        bool isExistUserAndPass(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistUserAndPass", ReplyAction="http://tempuri.org/IService1/isExistUserAndPassResponse")]
        System.Threading.Tasks.Task<bool> isExistUserAndPassAsync(string username, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deleteuser", ReplyAction="http://tempuri.org/IService1/DeleteuserResponse")]
        void Deleteuser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deleteuser", ReplyAction="http://tempuri.org/IService1/DeleteuserResponse")]
        System.Threading.Tasks.Task DeleteuserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Adduser", ReplyAction="http://tempuri.org/IService1/AdduserResponse")]
        void Adduser(string username, string password, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Adduser", ReplyAction="http://tempuri.org/IService1/AdduserResponse")]
        System.Threading.Tasks.Task AdduserAsync(string username, string password, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(string username, string password, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(string username, string password, string phonenumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllUser", ReplyAction="http://tempuri.org/IService1/showAllUserResponse")]
        System.Data.DataSet showAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllUser", ReplyAction="http://tempuri.org/IService1/showAllUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showUser", ReplyAction="http://tempuri.org/IService1/showUserResponse")]
        System.Data.DataSet showUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showUser", ReplyAction="http://tempuri.org/IService1/showUserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showUserByEmail", ReplyAction="http://tempuri.org/IService1/showUserByEmailResponse")]
        System.Data.DataSet showUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showUserByEmail", ReplyAction="http://tempuri.org/IService1/showUserByEmailResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        void DeleteProduct(string productcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(string productcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistProduct", ReplyAction="http://tempuri.org/IService1/isExistProductResponse")]
        bool isExistProduct(string productcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistProduct", ReplyAction="http://tempuri.org/IService1/isExistProductResponse")]
        System.Threading.Tasks.Task<bool> isExistProductAsync(string productcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProducts", ReplyAction="http://tempuri.org/IService1/showAllProductsResponse")]
        System.Data.DataSet showAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProducts", ReplyAction="http://tempuri.org/IService1/showAllProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsByCategory", ReplyAction="http://tempuri.org/IService1/showAllProductsByCategoryResponse")]
        System.Data.DataSet showAllProductsByCategory(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsByCategory", ReplyAction="http://tempuri.org/IService1/showAllProductsByCategoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsByCategoryAsync(string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsBy", ReplyAction="http://tempuri.org/IService1/showAllProductsByResponse")]
        System.Data.DataSet showAllProductsBy(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsBy", ReplyAction="http://tempuri.org/IService1/showAllProductsByResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsByAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        void AddProduct(string productcode, string productname, string category, string ProdImage, int prodprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(string productcode, string productname, string category, string ProdImage, int prodprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsInnerJoin", ReplyAction="http://tempuri.org/IService1/showAllProductsInnerJoinResponse")]
        System.Data.DataSet showAllProductsInnerJoin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllProductsInnerJoin", ReplyAction="http://tempuri.org/IService1/showAllProductsInnerJoinResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsInnerJoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        void UpdateProduct(string productcode, string productname, string category, string ProdImage, int prodprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(string productcode, string productname, string category, string ProdImage, int prodprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCategory", ReplyAction="http://tempuri.org/IService1/showAllCategoryResponse")]
        System.Data.DataSet showAllCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCategory", ReplyAction="http://tempuri.org/IService1/showAllCategoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategory", ReplyAction="http://tempuri.org/IService1/UpdateCategoryResponse")]
        void UpdateCategory(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCategory", ReplyAction="http://tempuri.org/IService1/UpdateCategoryResponse")]
        System.Threading.Tasks.Task UpdateCategoryAsync(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        void DeleteCategory(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        System.Threading.Tasks.Task DeleteCategoryAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        void AddCategory(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCategory", ReplyAction="http://tempuri.org/IService1/AddCategoryResponse")]
        System.Threading.Tasks.Task AddCategoryAsync(string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCategoryByCode", ReplyAction="http://tempuri.org/IService1/showAllCategoryByCodeResponse")]
        System.Data.DataSet showAllCategoryByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCategoryByCode", ReplyAction="http://tempuri.org/IService1/showAllCategoryByCodeResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllCategoryByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistCategory", ReplyAction="http://tempuri.org/IService1/isExistCategoryResponse")]
        bool isExistCategory(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistCategory", ReplyAction="http://tempuri.org/IService1/isExistCategoryResponse")]
        System.Threading.Tasks.Task<bool> isExistCategoryAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistProductInCart", ReplyAction="http://tempuri.org/IService1/isExistProductInCartResponse")]
        bool isExistProductInCart(string code, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isExistProductInCart", ReplyAction="http://tempuri.org/IService1/isExistProductInCartResponse")]
        System.Threading.Tasks.Task<bool> isExistProductInCartAsync(string code, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        void AddToCart(string ProdCode, string ProdName, double ProdPrice, string ProdImage, string username, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToCart", ReplyAction="http://tempuri.org/IService1/AddToCartResponse")]
        System.Threading.Tasks.Task AddToCartAsync(string ProdCode, string ProdName, double ProdPrice, string ProdImage, string username, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCartBy", ReplyAction="http://tempuri.org/IService1/showAllCartByResponse")]
        System.Data.DataSet showAllCartBy(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/showAllCartBy", ReplyAction="http://tempuri.org/IService1/showAllCartByResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> showAllCartByAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFromCart", ReplyAction="http://tempuri.org/IService1/DeleteFromCartResponse")]
        void DeleteFromCart(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFromCart", ReplyAction="http://tempuri.org/IService1/DeleteFromCartResponse")]
        System.Threading.Tasks.Task DeleteFromCartAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFromCart2", ReplyAction="http://tempuri.org/IService1/DeleteFromCart2Response")]
        void DeleteFromCart2(string prodCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFromCart2", ReplyAction="http://tempuri.org/IService1/DeleteFromCart2Response")]
        System.Threading.Tasks.Task DeleteFromCart2Async(string prodCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCart", ReplyAction="http://tempuri.org/IService1/UpdateCartResponse")]
        void UpdateCart(int quantity, string prodCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCart", ReplyAction="http://tempuri.org/IService1/UpdateCartResponse")]
        System.Threading.Tasks.Task UpdateCartAsync(int quantity, string prodCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/copyData", ReplyAction="http://tempuri.org/IService1/copyDataResponse")]
        void copyData(string username, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/copyData", ReplyAction="http://tempuri.org/IService1/copyDataResponse")]
        System.Threading.Tasks.Task copyDataAsync(string username, double price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApp1.ServiceReference1.IService1>, WpfApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WpfApp1.ServiceReference1.CompositeType GetDataUsingDataContract(WpfApp1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WpfApp1.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool isExistUser(string username) {
            return base.Channel.isExistUser(username);
        }
        
        public System.Threading.Tasks.Task<bool> isExistUserAsync(string username) {
            return base.Channel.isExistUserAsync(username);
        }
        
        public bool isExistUserAndPass(string username, string pass) {
            return base.Channel.isExistUserAndPass(username, pass);
        }
        
        public System.Threading.Tasks.Task<bool> isExistUserAndPassAsync(string username, string pass) {
            return base.Channel.isExistUserAndPassAsync(username, pass);
        }
        
        public void Deleteuser(string username) {
            base.Channel.Deleteuser(username);
        }
        
        public System.Threading.Tasks.Task DeleteuserAsync(string username) {
            return base.Channel.DeleteuserAsync(username);
        }
        
        public void Adduser(string username, string password, string phonenumber, string email) {
            base.Channel.Adduser(username, password, phonenumber, email);
        }
        
        public System.Threading.Tasks.Task AdduserAsync(string username, string password, string phonenumber, string email) {
            return base.Channel.AdduserAsync(username, password, phonenumber, email);
        }
        
        public void UpdateUser(string username, string password, string phonenumber, string email) {
            base.Channel.UpdateUser(username, password, phonenumber, email);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(string username, string password, string phonenumber, string email) {
            return base.Channel.UpdateUserAsync(username, password, phonenumber, email);
        }
        
        public System.Data.DataSet showAllUser() {
            return base.Channel.showAllUser();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllUserAsync() {
            return base.Channel.showAllUserAsync();
        }
        
        public System.Data.DataSet showUser(string username) {
            return base.Channel.showUser(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showUserAsync(string username) {
            return base.Channel.showUserAsync(username);
        }
        
        public System.Data.DataSet showUserByEmail(string email) {
            return base.Channel.showUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showUserByEmailAsync(string email) {
            return base.Channel.showUserByEmailAsync(email);
        }
        
        public void DeleteProduct(string productcode) {
            base.Channel.DeleteProduct(productcode);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(string productcode) {
            return base.Channel.DeleteProductAsync(productcode);
        }
        
        public bool isExistProduct(string productcode) {
            return base.Channel.isExistProduct(productcode);
        }
        
        public System.Threading.Tasks.Task<bool> isExistProductAsync(string productcode) {
            return base.Channel.isExistProductAsync(productcode);
        }
        
        public System.Data.DataSet showAllProducts() {
            return base.Channel.showAllProducts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsAsync() {
            return base.Channel.showAllProductsAsync();
        }
        
        public System.Data.DataSet showAllProductsByCategory(string category) {
            return base.Channel.showAllProductsByCategory(category);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsByCategoryAsync(string category) {
            return base.Channel.showAllProductsByCategoryAsync(category);
        }
        
        public System.Data.DataSet showAllProductsBy(string code) {
            return base.Channel.showAllProductsBy(code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsByAsync(string code) {
            return base.Channel.showAllProductsByAsync(code);
        }
        
        public void AddProduct(string productcode, string productname, string category, string ProdImage, int prodprice) {
            base.Channel.AddProduct(productcode, productname, category, ProdImage, prodprice);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(string productcode, string productname, string category, string ProdImage, int prodprice) {
            return base.Channel.AddProductAsync(productcode, productname, category, ProdImage, prodprice);
        }
        
        public System.Data.DataSet showAllProductsInnerJoin() {
            return base.Channel.showAllProductsInnerJoin();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllProductsInnerJoinAsync() {
            return base.Channel.showAllProductsInnerJoinAsync();
        }
        
        public void UpdateProduct(string productcode, string productname, string category, string ProdImage, int prodprice) {
            base.Channel.UpdateProduct(productcode, productname, category, ProdImage, prodprice);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(string productcode, string productname, string category, string ProdImage, int prodprice) {
            return base.Channel.UpdateProductAsync(productcode, productname, category, ProdImage, prodprice);
        }
        
        public System.Data.DataSet showAllCategory() {
            return base.Channel.showAllCategory();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllCategoryAsync() {
            return base.Channel.showAllCategoryAsync();
        }
        
        public void UpdateCategory(string code, string name) {
            base.Channel.UpdateCategory(code, name);
        }
        
        public System.Threading.Tasks.Task UpdateCategoryAsync(string code, string name) {
            return base.Channel.UpdateCategoryAsync(code, name);
        }
        
        public void DeleteCategory(string code) {
            base.Channel.DeleteCategory(code);
        }
        
        public System.Threading.Tasks.Task DeleteCategoryAsync(string code) {
            return base.Channel.DeleteCategoryAsync(code);
        }
        
        public void AddCategory(string code, string name) {
            base.Channel.AddCategory(code, name);
        }
        
        public System.Threading.Tasks.Task AddCategoryAsync(string code, string name) {
            return base.Channel.AddCategoryAsync(code, name);
        }
        
        public System.Data.DataSet showAllCategoryByCode(string code) {
            return base.Channel.showAllCategoryByCode(code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllCategoryByCodeAsync(string code) {
            return base.Channel.showAllCategoryByCodeAsync(code);
        }
        
        public bool isExistCategory(string code) {
            return base.Channel.isExistCategory(code);
        }
        
        public System.Threading.Tasks.Task<bool> isExistCategoryAsync(string code) {
            return base.Channel.isExistCategoryAsync(code);
        }
        
        public bool isExistProductInCart(string code, string username) {
            return base.Channel.isExistProductInCart(code, username);
        }
        
        public System.Threading.Tasks.Task<bool> isExistProductInCartAsync(string code, string username) {
            return base.Channel.isExistProductInCartAsync(code, username);
        }
        
        public void AddToCart(string ProdCode, string ProdName, double ProdPrice, string ProdImage, string username, int quantity) {
            base.Channel.AddToCart(ProdCode, ProdName, ProdPrice, ProdImage, username, quantity);
        }
        
        public System.Threading.Tasks.Task AddToCartAsync(string ProdCode, string ProdName, double ProdPrice, string ProdImage, string username, int quantity) {
            return base.Channel.AddToCartAsync(ProdCode, ProdName, ProdPrice, ProdImage, username, quantity);
        }
        
        public System.Data.DataSet showAllCartBy(string username) {
            return base.Channel.showAllCartBy(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> showAllCartByAsync(string username) {
            return base.Channel.showAllCartByAsync(username);
        }
        
        public void DeleteFromCart(string username) {
            base.Channel.DeleteFromCart(username);
        }
        
        public System.Threading.Tasks.Task DeleteFromCartAsync(string username) {
            return base.Channel.DeleteFromCartAsync(username);
        }
        
        public void DeleteFromCart2(string prodCode, string username) {
            base.Channel.DeleteFromCart2(prodCode, username);
        }
        
        public System.Threading.Tasks.Task DeleteFromCart2Async(string prodCode, string username) {
            return base.Channel.DeleteFromCart2Async(prodCode, username);
        }
        
        public void UpdateCart(int quantity, string prodCode, string username) {
            base.Channel.UpdateCart(quantity, prodCode, username);
        }
        
        public System.Threading.Tasks.Task UpdateCartAsync(int quantity, string prodCode, string username) {
            return base.Channel.UpdateCartAsync(quantity, prodCode, username);
        }
        
        public void copyData(string username, double price) {
            base.Channel.copyData(username, price);
        }
        
        public System.Threading.Tasks.Task copyDataAsync(string username, double price) {
            return base.Channel.copyDataAsync(username, price);
        }
    }
}
